### ISSUE TITLE
Allow using `tsconfig.json` with comments and tailing commas

### ISSUE THREAD

**Issue by AgainPsychoX** [jonkwheeler/tsconfig-replace-paths#10]
Allow on comments in `tsconfig.json`.

### Motivation 

While it's not officially proper to have them in JSON files, many people use comments in some JSON files, and node and tsc with those without problem. The same for tailing commas.

### Problem example
_(yeah, even GitHub highlighting for `json` does not like them, but imo still should be allowed)_:
```json
{
	"compilerOptions": {
		"baseUrl": "./",
		"outDir": "./dist",
		"paths": {
			"@/*": ["./src/*"],
		},

		"target": "ES2020",
		"module": "ES2020",
		"moduleResolution": "Node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"lib": ["ES2020"],
		"types": [
			"node"
		],
		"strict": true,
		"declaration": false,
		"skipLibCheck": true,
		"esModuleInterop": true,
		"incremental": true,

		"allowSyntheticDefaultImports": true,
		"noUnusedLocals": true,
		"noUnusedParameters": false,
		"noImplicitReturns": true,
		"noFallthroughCasesInSwitch": true,
		"noUncheckedIndexedAccess": true,
		"noImplicitOverride": true
		// "strictPropertyInitialization": false
	},
	"include": ["src"]
}
```

Error now:
```node
> tsc && tsconfig-replace-paths --project tsconfig.json

Using tsconfig: D:\Projects\opgg-data-miner\tsconfig.json
node:internal/modules/cjs/loader:1155
    throw err;
    ^

SyntaxError: D:\Projects\opgg-data-miner\tsconfig.json: Unexpected token } in JSON at position 109
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1152:22)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.exports.loadConfig (D:\Projects\opgg-data-miner\node_modules\tsconfig-replace-paths\dist\commonjs\util.js:17:12)
    at Object.<anonymous> (D:\Projects\opgg-data-miner\node_modules\tsconfig-replace-paths\dist\commonjs\index.js:43:33)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
```

### Implementation

I suggest to use something like https://json5.org/

**Comment by jgod** [comment]
JSON5 may be too radical (allowing single quoted strings, etc.). We can start with just stripping comments, which can be done in a few lines without any dependencies

**Comment by jonkwheeler** [comment]
FYI, on vacation right now, but will come back to this when time permits. Thanks for understanding.

**Comment by Xunnamius** [comment]
@jonkwheeler #13 should fix this :)

**Comment by vic1707** [comment]
My file is in the first comment (as tsconfig.txt)

**Comment by jonkwheeler** [comment]
I just merged https://github.com/jonkwheeler/tsconfig-replace-paths/pull/18

0.0.9

Want to see if it helps? Uses the JSON5 package.
